// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkAd.Data;

#nullable disable

namespace WorkAd.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260625061109_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("WorkAd.Data.WorkAdvert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("HourlyRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.ToTable("WorkAdvert");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContractType = 1,
                            CreatedDate = new DateTime(2026, 6, 20, 6, 11, 9, 569, DateTimeKind.Utc).AddTicks(7954),
                            Description = "We are looking for a salesperson to work in our drugstore. The candidate should have experience in sales and customer service.",
                            HourlyRate = 3200L,
                            Location = "Warsaw",
                            Title = "Drugstore salesperson",
                            WorkType = 1
                        },
                        new
                        {
                            Id = 2,
                            ContractType = 3,
                            CreatedDate = new DateTime(2026, 6, 13, 6, 11, 9, 569, DateTimeKind.Utc).AddTicks(7959),
                            Description = "We are looking for a junior web developer to join our remote development team. Basic knowledge of HTML, CSS, and C# is required.",
                            HourlyRate = 4550L,
                            Location = "Gdańsk",
                            Title = "Junior Web Developer",
                            WorkType = 0
                        },
                        new
                        {
                            Id = 3,
                            ContractType = 2,
                            CreatedDate = new DateTime(2026, 6, 23, 6, 11, 9, 569, DateTimeKind.Utc).AddTicks(7962),
                            Description = "A warehouse assistant is needed for packaging, sorting and preparing shipments. No experience required, training provided.",
                            HourlyRate = 3750L,
                            Location = "Poznań",
                            Title = "Warehouse Assistant",
                            WorkType = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
